name: SemVer
on:
  push: 
    branches: [ $default-branch ]
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]
    branches: [$default-branch]

  workflow_dispatch:

permissions: {}

jobs:
  semver-validate-bump:
    name: Semver
    uses: ArchetypicalSoftware/github-workflows/.github/workflows/semver.yml@main
    permissions:
      contents: write
      pull-requests: read
    secrets: inherit